const jobListings = [
  {
    id: 1,
    title: "Software Engineer",
    description: "We are seeking a skilled Software Engineer to join our dynamic development team. As a Software Engineer, you will be responsible for designing, developing, and maintaining high-quality software solutions. You will collaborate with cross-functional teams to gather requirements, analyze user needs, and implement innovative software solutions. The ideal candidate has a strong background in software development, excellent problem-solving skills, and a passion for creating cutting-edge applications.",
    salary: "8-10 LPA",
    companyName:"Amazon" ,
    duration: "Full-time",
    experience: "3-5 years",
    location: "San Francisco, CA",
    requirements: "Bachelor's degree in Computer Science or related field...",
    skills: ["JavaScript", "React", "Node.js", "SQL"],
    role: "Software Development",
    industryType: "Information Technology",
    roleCategory: "Programming & Design",
    education: "Bachelor's degree",
    keySkills: ["JavaScript", "React", "Node.js", "SQL"],
    employmentType: "Full-time",
    postDateTime: "2023-06-01T09:00:00Z",
    applicants: 12,
  },
  {
    id: 2,
    title: "Marketing Specialist",
    description: "We are seeking a skilled Software Engineer to join our dynamic development team. As a Software Engineer, you will be responsible for designing, developing, and maintaining high-quality software solutions. You will collaborate with cross-functional teams to gather requirements, analyze user needs, and implement innovative software solutions. The ideal candidate has a strong background in software development, excellent problem-solving skills, and a passion for creating cutting-edge applications.",
    salary: "6-8 LPA",
    companyName:"ITC" ,
    duration: "Contract",
    experience: "2-4 years",
    location: "Mumbai, India",
    requirements: "Bachelor's degree in Marketing or related field...",
    skills: ["Digital Marketing", "SEO", "Social Media"],
    role: "Marketing",
    industryType: "Advertising",
    roleCategory: "Marketing & Design",
    education: "Bachelor's degree",
    keySkills: ["Digital Marketing", "SEO", "Social Media"],
    employmentType: "Contract",
    postDateTime: "2023-06-02T13:30:00Z",
    applicants: 8,
  },

   {
    id: 3,
    title: "Graphic Designer",
    description: "We are seeking a skilled Software Engineer to join our dynamic development team. As a Software Engineer, you will be responsible for designing, developing, and maintaining high-quality software solutions. You will collaborate with cross-functional teams to gather requirements, analyze user needs, and implement innovative software solutions. The ideal candidate has a strong background in software development, excellent problem-solving skills, and a passion for creating cutting-edge applications.",
    salary: "5-7 LPA",
    companyName:"Cred" ,
    duration: "Full-time",
    experience: "1-3 years",
    location: "Bangalore, India",
    requirements: "Bachelor's degree in Graphic Design or related field...",
    skills: ["Adobe Photoshop", "Illustrator", "InDesign"],
    role: "Design",
    industryType: "Graphic Design",
    roleCategory: "Art & Design",
    education: "Bachelor's degree",
    keySkills: ["Adobe Photoshop", "Illustrator", "InDesign"],
    employmentType: "Full-time",
    postDateTime: "2023-06-03T10:45:00Z",
    applicants: 5,
  },
  {
    id: 4,
    title: "Financial Analyst",
    description: "We are seeking a skilled Software Engineer to join our dynamic development team. As a Software Engineer, you will be responsible for designing, developing, and maintaining high-quality software solutions. You will collaborate with cross-functional teams to gather requirements, analyze user needs, and implement innovative software solutions. The ideal candidate has a strong background in software development, excellent problem-solving skills, and a passion for creating cutting-edge applications.",
    salary: "7-9 LPA",
    companyName:"Zerodha" ,
    duration: "Permanent",

    experience: "2-5 years",
    location: "Bangalore, IL",
    requirements: "Bachelor's degree in Finance or related field...",
    skills: ["Financial Analysis", "Excel", "Budgeting"],
    role: "Finance",
    industryType: "Banking/Finance",
    roleCategory: "Finance & Accounting",
    education: "Bachelor's degree",
    keySkills: ["Financial Analysis", "Excel", "Budgeting"],
    employmentType: "Permanent",
    postDateTime: "2023-06-04T14:15:00Z",
    applicants: 10,
  },
  {
    id: 5,
    title: "Sales Manager",
    description: "We are seeking a skilled Software Engineer to join our dynamic development team. As a Software Engineer, you will be responsible for designing, developing, and maintaining high-quality software solutions. You will collaborate with cross-functional teams to gather requirements, analyze user needs, and implement innovative software solutions. The ideal candidate has a strong background in software development, excellent problem-solving skills, and a passion for creating cutting-edge applications.",
    salary: "9-12 LPA",
    companyName:`Interview Ready` ,
    duration: "Full-time",
    experience: "5-8 years",
    location: "Pune, India",
    requirements: "Bachelor's degree in Business or related field...",
    skills: ["Sales Management", "Business Development", "Negotiation"],
    role: "Sales",
    industryType: "Retail",
    roleCategory: "Sales & Business Development",
    education: "Bachelor's degree",
    keySkills: ["Sales Management", "Business Development", "Negotiation"],
    employmentType: "Full-time",
    postDateTime: "2023-06-05T09:30:00Z",
    applicants: 7,
  },
  {
    id: 6,
    title: "Human Resources Coordinator",
    description: "We are seeking a skilled Software Engineer to join our dynamic development team. As a Software Engineer, you will be responsible for designing, developing, and maintaining high-quality software solutions. You will collaborate with cross-functional teams to gather requirements, analyze user needs, and implement innovative software solutions. The ideal candidate has a strong background in software development, excellent problem-solving skills, and a passion for creating cutting-edge applications.",
    salary: "4-5 LPA",
    companyName:"Appdeployer" ,
    duration: "Permanent",
    experience: "0-2 years",
    location: "Indore , India",
    requirements: "Bachelor's degree in Human Resources or related field...",
    skills: ["HR Administration", "Recruitment", "Employee Relations"],
    role: "Human Resources",
    industryType: "Human Resources",
    roleCategory: "HR & Recruitment",
    education: "Bachelor's degree",
    keySkills: ["HR Administration", "Recruitment", "Employee Relations"],
    employmentType: "Permanent",
    postDateTime: "2023-06-06T12:00:00Z",
    applicants: 3,
  },
  {
    id: 7,
    title: "Customer Service Representative",
    description: "We are seeking a skilled Software Engineer to join our dynamic development team. As a Software Engineer, you will be responsible for designing, developing, and maintaining high-quality software solutions. You will collaborate with cross-functional teams to gather requirements, analyze user needs, and implement innovative software solutions. The ideal candidate has a strong background in software development, excellent problem-solving skills, and a passion for creating cutting-edge applications.",
    salary: "10-30 LPA",
    companyName:"Flipkart" ,
    duration: "Full-time",
    experience: "0-1 years",
    location: "Bangalore, India",
    requirements: "High school diploma or equivalent...",
    skills: ["Customer Service", "Problem-solving", "Communication"],
    role: "Customer Service",
    industryType: "Customer Service",
    roleCategory: "Customer Support",
    education: "High school diploma",
    keySkills: ["Customer Service", "Problem-solving", "Communication"],
    employmentType: "Full-time",
    postDateTime: "2023-06-07T15:45:00Z",
    applicants: 6,
  },
  {
    id: 8,
    title: "Data Analyst",
    description: "We are seeking a skilled Software Engineer to join our dynamic development team. As a Software Engineer, you will be responsible for designing, developing, and maintaining high-quality software solutions. You will collaborate with cross-functional teams to gather requirements, analyze user needs, and implement innovative software solutions. The ideal candidate has a strong background in software development, excellent problem-solving skills, and a passion for creating cutting-edge applications.",
    salary: "6-8 LPA",
    companyName:"Bajaj finserve" ,
    duration: "Contract",
    experience: "2-4 years",
    location: "Pune, India",
    requirements: "Bachelor's degree in Statistics or related field...",
    skills: ["Data Analysis", "SQL", "Excel"],
    role: "Data Analysis",
    industryType: "Technology",
    roleCategory: "Data & Analytics",
    education: "Bachelor's degree",
    keySkills: ["Data Analysis", "SQL", "Excel"],
    employmentType: "Contract",
    postDateTime: "2023-06-08T10:15:00Z",
    applicants: 9,
  },

  {
    id: 9,
    title: "Content writer",
    description: "We are seeking a skilled Software Engineer to join our dynamic development team. As a Software Engineer, you will be responsible for designing, developing, and maintaining high-quality software solutions. You will collaborate with cross-functional teams to gather requirements, analyze user needs, and implement innovative software solutions. The ideal candidate has a strong background in software development, excellent problem-solving skills, and a passion for creating cutting-edge applications.",
    salary: "9-12 LPA",
    companyName:"GFG" ,
    duration: "Full-time",
    experience: "5-8 years",
    location: "Bangalore, India",
    requirements: "Bachelor's degree in Business or related field...",
    skills: ["Sales Management", "Business Development", "Negotiation"],
    role: "Sales",
    industryType: "Retail",
    roleCategory: "Sales & Business Development",
    education: "Bachelor's degree",
    keySkills: ["Sales Management", "Business Development", "Negotiation"],
    employmentType: "Full-time",
    postDateTime: "2023-06-05T09:30:00Z",
    applicants: 7,
  },
  {
    id: 10,
    title: "Assistant proffessor",
    description: "We are seeking a skilled Software Engineer to join our dynamic development team. As a Software Engineer, you will be responsible for designing, developing, and maintaining high-quality software solutions. You will collaborate with cross-functional teams to gather requirements, analyze user needs, and implement innovative software solutions. The ideal candidate has a strong background in software development, excellent problem-solving skills, and a passion for creating cutting-edge applications.",
    salary: "4-5 LPA",
    companyName:"LPU" ,
    duration: "Permanent",
    experience: "0-2 years",
    location: "Gwalior , India",
    requirements: "Master's or PHD degree in computer science or related field...",
    skills: ["Teaching", "Communication", "Leadership"],
    role: "Assistent Professor",
    industryType: "Teaching",
    roleCategory: "Assitent",
    education: "Master's degree",
    keySkills: ["Teaching", "Communication", "English speaking"],
    employmentType: "Permanent",
    postDateTime: "2023-06-06T12:00:00Z",
    applicants: 3,
  },
  {
  id: 11,
  title: "Graphic Designer",
  description: "We are seeking a skilled Software Engineer to join our dynamic development team. As a Software Engineer, you will be responsible for designing, developing, and maintaining high-quality software solutions. You will collaborate with cross-functional teams to gather requirements, analyze user needs, and implement innovative software solutions. The ideal candidate has a strong background in software development, excellent problem-solving skills, and a passion for creating cutting-edge applications.",
  salary: "5-6 LPA",
  companyName:"Dream 11" ,
  duration: "Full-time",
  experience: "1-3 years",
  location: "Mumbai , India",
  requirements: "Bachelor's degree in Graphic Design or related field...",
  skills: ["Adobe Creative Suite", "Typography", "Visual Communication"],
  role: "Graphic Design",
  industryType: "Design",
  roleCategory: "Graphic Design",
  education: "Bachelor's degree",
  keySkills: ["Adobe Creative Suite", "Typography", "Visual Communication"],
  employmentType: "Full-time",
  postDateTime: "2023-06-11T14:00:00Z",
  applicants: 5,
},
{
  id: 12,
  title: "Project Manager",
  description: "We are seeking a skilled Software Engineer to join our dynamic development team. As a Software Engineer, you will be responsible for designing, developing, and maintaining high-quality software solutions. You will collaborate with cross-functional teams to gather requirements, analyze user needs, and implement innovative software solutions. The ideal candidate has a strong background in software development, excellent problem-solving skills, and a passion for creating cutting-edge applications.",
  salary: "9 -11 LPA",
  companyName:"Google" ,
  duration: "Contract",
  experience: "5-8 years",
  location: "Bangalore, India",
  requirements: "Bachelor's degree in Project Management or related field...",
  skills: ["Project Planning", "Team Management", "Risk Assessment"],
  role: "Project Management",
  industryType: "Management",
  roleCategory: "Project Management",
  education: "Bachelor's degree",
  keySkills: ["Project Planning", "Team Management", "Risk Assessment"],
  employmentType: "Contract",
  postDateTime: "2023-06-12T16:30:00Z",
  applicants: 10,
}
  
];

export default jobListings;
